from pathlib import Path
from collections import Counter
import csv
import re

import pandas as pd

PASTA = Path(r"D:\Downloads")

ARQUIVOS_ENTRADA = {
    "merged_df": PASTA / "merged_df_pmi.csv",
    "pagode": PASTA / "pagode_pmi.csv",
    "sertanejo": PASTA / "sertanejo_pmi.csv",
    "forro": PASTA / "forro_pmi.csv",
    "funk": PASTA / "funk_pmi.csv",
    "mpb": PASTA / "mpb_pmi.csv",
}

ARQUIVOS_SAIDA = {
    "merged_df": PASTA / "merged_df_pmi_substituido.csv",
    "pagode": PASTA / "pagode_pmi_substituido.csv",
    "sertanejo": PASTA / "sertanejo_pmi_substituido.csv",
    "forro": PASTA / "forro_pmi_substituido.csv",
    "funk": PASTA / "funk_pmi_substituido.csv",
    "mpb": PASTA / "mpb_pmi_substituido.csv",
}

CHUNKSIZE = 10000

CONTAGEM_SUBSTITUICOES = Counter()

# -------------------------------------------------------------------------
# LISTA CODIFICADA NO PRÓPRIO SCRIPT
# Este código utiliza ALVOS.
# Este código NÃO utiliza ATRIBUTOS.
#
# Fonte consolidada: lista atualizada, já sem alvos duplicados.
# Total: 1.569 alvos únicos.
# -------------------------------------------------------------------------
ALVOS_POR_CLASSIFICACAO = {'ela_similares': ['baby',
                   'condessa',
                   'dama',
                   'damas',
                   'dela',
                   'delas',
                   'dona',
                   'donas',
                   'ela',
                   'elas',
                   'fêmea',
                   'fêmeas',
                   'garota',
                   'garotas',
                   'garotinha',
                   'madame',
                   'madames',
                   'menina',
                   'meninas',
                   'menininha',
                   'mina',
                   'minas',
                   'mocinha',
                   'moça',
                   'moças',
                   'mulata',
                   'mulatinha',
                   'mulher',
                   'mulherada',
                   'mulheres',
                   'mulherzinha',
                   'nega',
                   'negona',
                   'neguinha',
                   'rainha',
                   'rainhas',
                   'senhora',
                   'senhoras',
                   'senhorinha',
                   'senhorita',
                   'senhoritas',
                   'sinhá',
                   'vizinha',
                   'vizinhas'],
 'ele_similares': ['cara',
                   'caras',
                   'dele',
                   'deles',
                   'dono',
                   'doutor',
                   'doutorzinho',
                   'ele',
                   'eles',
                   'garotinho',
                   'garoto',
                   'garotão',
                   'homem',
                   'homens',
                   'macho',
                   'machos',
                   'machão',
                   'maninho',
                   'mano',
                   'manos',
                   'mané',
                   'menininho',
                   'menino',
                   'meninão',
                   'mocinho',
                   'molecão',
                   'moleque',
                   'moleques',
                   'molequinho',
                   'moço',
                   'moços',
                   'mulato',
                   'muleke',
                   'nego',
                   'neguinho',
                   'negão',
                   'patrão',
                   'patrãozinho',
                   'peão',
                   'rapaizinho',
                   'rapaz',
                   'rapazes',
                   'rapaziada',
                   'rapazinho',
                   'rei',
                   'reis',
                   'reizinho',
                   'senhor',
                   'sinhô',
                   'vizinho'],
 'familia_fem': ['avó',
                 'avós',
                 'casada',
                 'casadas',
                 'esposa',
                 'esposas',
                 'filha',
                 'filhas',
                 'filhinha',
                 'gêmeas',
                 'irmã',
                 'irmãs',
                 'irmãzinha',
                 'madrinha',
                 'mainha',
                 'mamãe',
                 'mamães',
                 'mamãezinha',
                 'mana',
                 'manas',
                 'maninha',
                 'mãe',
                 'mães',
                 'mãezinha',
                 'namorada',
                 'namoradas',
                 'namoradinha',
                 'noiva',
                 'nora',
                 'novinha',
                 'novinhas',
                 'prima',
                 'sobrinha',
                 'sobrinhas',
                 'tia',
                 'tias',
                 'tiazinha',
                 'titia',
                 'viúvas',
                 'vovozinha',
                 'vovó'],
 'familia_masc': ['avozinho',
                  'avô',
                  'compadre',
                  'cumpade',
                  'cumpadre',
                  'filhinho',
                  'filho',
                  'filhão',
                  'genro',
                  'genros',
                  'irmão',
                  'irmãozinho',
                  'irmãozão',
                  'maridinho',
                  'marido',
                  'maridos',
                  'maridão',
                  'namoradinho',
                  'namorado',
                  'netinho',
                  'pai',
                  'painho',
                  'paizinho',
                  'paizão',
                  'papai',
                  'papaizinho',
                  'primo',
                  'sobrinho',
                  'sogro',
                  'sogrão',
                  'tio',
                  'tios',
                  'tiozinho',
                  'tiozão',
                  'titio',
                  'vovozinho',
                  'vovô'],
 'nome_fem': ['abigail',
              'adelaide',
              'adelia',
              'adelina',
              'adria',
              'adriana',
              'adriane',
              'adriely',
              'agata',
              'agatha',
              'agda',
              'aila',
              'alaide',
              'alana',
              'alba',
              'albertina',
              'alcione',
              'alda',
              'alessandra',
              'alexandra',
              'alexia',
              'alice',
              'alicia',
              'aline',
              'alzira',
              'amalia',
              'amanda',
              'amara',
              'amelia',
              'ana',
              'analia',
              'analu',
              'ananda',
              'andrea',
              'andreia',
              'andressa',
              'andreza',
              'ane',
              'angela',
              'angelica',
              'angelina',
              'angelita',
              'anita',
              'anna',
              'anne',
              'anny',
              'antonela',
              'antonella',
              'antonia',
              'antonieta',
              'any',
              'aparecida',
              'araci',
              'ariana',
              'ariane',
              'arlete',
              'augusta',
              'aurea',
              'aurora',
              'ayla',
              'barbara',
              'beatriz',
              'benedita',
              'berenice',
              'bernadete',
              'betania',
              'bianca',
              'brenda',
              'bruna',
              'cacilda',
              'camila',
              'camile',
              'camilla',
              'candida',
              'carina',
              'carine',
              'carla',
              'carmelita',
              'carmem',
              'carmen',
              'carol',
              'carolina',
              'caroline',
              'cassia',
              'catarina',
              'catia',
              'catiane',
              'cecilia',
              'celeste',
              'celi',
              'celia',
              'celina',
              'cilene',
              'cintia',
              'clair',
              'clara',
              'clarice',
              'clarissa',
              'clarisse',
              'claudete',
              'claudia',
              'claudiane',
              'cleide',
              'cleonice',
              'cleunice',
              'cleusa',
              'conceicao',
              'cremilda',
              'creusa',
              'creuza',
              'cristiana',
              'cristiane',
              'cristina',
              'daiana',
              'daiane',
              'dalila',
              'dalva',
              'damiana',
              'dandara',
              'daniela',
              'daniele',
              'daniella',
              'danielle',
              'danielly',
              'danubia',
              'dara',
              'darlene',
              'dayana',
              'dayane',
              'dayse',
              'debora',
              'deborah',
              'deise',
              'delma',
              'denise',
              'diana',
              'diane',
              'dilma',
              'dina',
              'dinalva',
              'dione',
              'dirce',
              'diva',
              'divina',
              'dolores',
              'domingas',
              'dora',
              'doralice',
              'dulce',
              'dulcineia',
              'edilane',
              'edilene',
              'edileusa',
              'edileuza',
              'edite',
              'edna',
              'eduarda',
              'efigenia',
              'elaine',
              'elen',
              'elena',
              'eliana',
              'eliane',
              'elida',
              'eliete',
              'elis',
              'elisa',
              'elisabeth',
              'elisangela',
              'elisete',
              'eliza',
              'elizabete',
              'elizabeth',
              'elizandra',
              'elizete',
              'ellen',
              'eloa',
              'eloisa',
              'eloise',
              'elsa',
              'elvira',
              'elza',
              'emanuela',
              'emanuele',
              'emanuelle',
              'emanuely',
              'emili',
              'emilia',
              'emilly',
              'emily',
              'eni',
              'erica',
              'erika',
              'esmeralda',
              'estela',
              'ester',
              'esther',
              'eugenia',
              'eunice',
              'eurides',
              'eva',
              'evelyn',
              'fabiana',
              'fabiane',
              'fabiola',
              'fatima',
              'fernanda',
              'filomena',
              'flavia',
              'flaviana',
              'flora',
              'franciele',
              'francieli',
              'francine',
              'francisca',
              'gabriela',
              'gabriele',
              'gabriella',
              'gabrielle',
              'gabrielly',
              'geni',
              'genilda',
              'geovana',
              'geovanna',
              'geralda',
              'gerlane',
              'gessica',
              'gilda',
              'gilmara',
              'giovana',
              'giovanna',
              'gisele',
              'giseli',
              'giselle',
              'gislaine',
              'giulia',
              'gleice',
              'gloria',
              'graziela',
              'guiomar',
              'hadassa',
              'hanna',
              'helen',
              'helena',
              'helia',
              'hellen',
              'heloisa',
              'hilda',
              'hosana',
              'iara',
              'iasmin',
              'idalina',
              'ieda',
              'inacia',
              'ines',
              'ingrid',
              'iolanda',
              'ione',
              'iracema',
              'iraci',
              'irene',
              'iris',
              'irma',
              'isa',
              'isabel',
              'isabela',
              'isabele',
              'isabella',
              'isabelle',
              'isabelly',
              'isadora',
              'isaura',
              'isis',
              'ivete',
              'ivone',
              'ivonete',
              'izabel',
              'izabela',
              'izabella',
              'izaura',
              'jaci',
              'jaciara',
              'jacinta',
              'jacira',
              'jackeline',
              'jacqueline',
              'jade',
              'jamili',
              'janaina',
              'jandira',
              'jane',
              'janete',
              'janice',
              'jaqueline',
              'jenifer',
              'jennifer',
              'jessica',
              'joana',
              'joaquina',
              'joelma',
              'joice',
              'jordana',
              'josefa',
              'josefina',
              'joseli',
              'josiane',
              'josilene',
              'jovelina',
              'joyce',
              'judite',
              'julia',
              'juliana',
              'juliane',
              'juliene',
              'julieta',
              'juliete',
              'juraci',
              'jurema',
              'jussara',
              'kamila',
              'karen',
              'karina',
              'karine',
              'karla',
              'karolina',
              'karoline',
              'kassia',
              'katia',
              'kelly',
              'kely',
              'ketlin',
              'keyla',
              'kiara',
              'kimberly',
              'laila',
              'lais',
              'lana',
              'lara',
              'larisa',
              'larissa',
              'laryssa',
              'laura',
              'lauren',
              'laurinda',
              'lays',
              'laysa',
              'lea',
              'leandra',
              'leda',
              'leia',
              'leide',
              'leila',
              'leni',
              'lenilda',
              'lenir',
              'leonilda',
              'leonor',
              'leticia',
              'lia',
              'liana',
              'liane',
              'lidia',
              'lidiane',
              'ligia',
              'lilia',
              'lilian',
              'liliana',
              'liliane',
              'linda',
              'lindalva',
              'lindaura',
              'lindinalva',
              'lis',
              'livia',
              'liz',
              'lorena',
              'lorraine',
              'lorrayne',
              'louise',
              'lourdes',
              'luana',
              'luara',
              'lucelia',
              'luci',
              'lucia',
              'luciana',
              'luciene',
              'lucila',
              'lucilia',
              'lucimar',
              'lucimara',
              'lucineide',
              'ludmila',
              'luisa',
              'luiza',
              'luma',
              'luna',
              'lunna',
              'lurdes',
              'luzia',
              'luzinete',
              'madalena',
              'magali',
              'magda',
              'magna',
              'maia',
              'maiara',
              'maira',
              'maisa',
              'maite',
              'malu',
              'manoela',
              'manuela',
              'mara',
              'marcela',
              'marcele',
              'marcella',
              'marcelle',
              'marcia',
              'marciana',
              'margarete',
              'margareth',
              'margarida',
              'mari',
              'maria',
              'mariah',
              'mariana',
              'mariane',
              'mariele',
              'marilda',
              'marileide',
              'marilena',
              'marilia',
              'marina',
              'marinalva',
              'marines',
              'marinete',
              'marisa',
              'maristela',
              'mariza',
              'marizete',
              'marlene',
              'marli',
              'marluce',
              'marly',
              'marta',
              'martha',
              'mary',
              'matilde',
              'maura',
              'maya',
              'mayara',
              'mayra',
              'maysa',
              'meire',
              'melina',
              'melissa',
              'mercedes',
              'michele',
              'micheli',
              'michelle',
              'michelly',
              'mikaela',
              'milena',
              'milene',
              'millena',
              'mirela',
              'mirella',
              'miria',
              'miriam',
              'mirian',
              'monalisa',
              'monica',
              'monique',
              'morgana',
              'nadir',
              'naiara',
              'nair',
              'nara',
              'natalia',
              'natalina',
              'natasha',
              'nathalia',
              'nayane',
              'nayara',
              'nazare',
              'neide',
              'neiva',
              'neli',
              'neusa',
              'neuza',
              'nicole',
              'nicolle',
              'nilce',
              'nilsa',
              'nina',
              'nivea',
              'noelia',
              'noemi',
              'noemia',
              'norma',
              'nubia',
              'odete',
              'olga',
              'olinda',
              'olivia',
              'paloma',
              'pamela',
              'paola',
              'patricia',
              'paula',
              'paulina',
              'perola',
              'pietra',
              'poliana',
              'pricila',
              'priscila',
              'priscilla',
              'quiteria',
              'rachel',
              'rafaela',
              'raiane',
              'raimunda',
              'raissa',
              'raquel',
              'rayane',
              'rayssa',
              'rebeca',
              'rebecca',
              'regiane',
              'regina',
              'rejane',
              'renata',
              'renilda',
              'rita',
              'roberta',
              'romilda',
              'rosa',
              'rosalia',
              'rosalina',
              'rosana',
              'rosane',
              'rosangela',
              'rosaria',
              'rose',
              'rosemary',
              'rosemeire',
              'rosicleide',
              'rosimere',
              'rosinete',
              'rubia',
              'rute',
              'ruth',
              'sabrina',
              'safira',
              'salete',
              'samanta',
              'samantha',
              'samara',
              'samira',
              'sandra',
              'sandy',
              'santa',
              'sara',
              'sarah',
              'sebastiana',
              'selma',
              'severina',
              'sheila',
              'shirley',
              'silene',
              'silmara',
              'silva',
              'silvana',
              'silvania',
              'silvia',
              'simone',
              'sirlei',
              'socorro',
              'sofia',
              'solange',
              'sonia',
              'sophia',
              'soraia',
              'soraya',
              'stefani',
              'stela',
              'stella',
              'stephanie',
              'stephany',
              'sthefany',
              'suelen',
              'sueli',
              'suellen',
              'suely',
              'susana',
              'suzana',
              'suzane',
              'tabata',
              'taciana',
              'taina',
              'tainara',
              'tais',
              'taisa',
              'talia',
              'talita',
              'tamara',
              'tamires',
              'tania',
              'tatiana',
              'tatiane',
              'tayla',
              'taynara',
              'telma',
              'teresa',
              'teresinha',
              'tereza',
              'terezinha',
              'thaila',
              'thaina',
              'thainara',
              'thais',
              'thaisa',
              'thalia',
              'thalita',
              'thamires',
              'thayna',
              'thays',
              'therezinha',
              'valentina',
              'valeria',
              'valesca',
              'valquiria',
              'vanda',
              'vanderleia',
              'vanessa',
              'vania',
              'vanusa',
              'vera',
              'veridiana',
              'veronica',
              'vicentina',
              'victoria',
              'vilma',
              'virginia',
              'vitoria',
              'vivian',
              'viviane',
              'wanda',
              'wanessa',
              'yara',
              'yasmim',
              'yasmin',
              'yolanda',
              'zelia',
              'zenaide',
              'zilda',
              'zuleide'],
 'nome_masc': ['abel',
               'abner',
               'abraao',
               'abrao',
               'acacio',
               'adailton',
               'adair',
               'adalberto',
               'adalto',
               'adao',
               'adelar',
               'adelino',
               'adelmo',
               'adelson',
               'ademar',
               'ademir',
               'adenir',
               'adilson',
               'adir',
               'adolfo',
               'adriano',
               'adriel',
               'adryan',
               'adson',
               'afonso',
               'agenor',
               'agnaldo',
               'agostinho',
               'ailton',
               'airton',
               'alair',
               'alan',
               'albert',
               'albertino',
               'alberto',
               'albino',
               'alceu',
               'alcides',
               'alcir',
               'aldo',
               'alef',
               'alejandro',
               'alessandro',
               'alex',
               'alexander',
               'alexandre',
               'alfredo',
               'alison',
               'alisson',
               'allan',
               'almir',
               'almiro',
               'aloisio',
               'alonso',
               'altair',
               'altamiro',
               'aluisio',
               'alvaro',
               'alysson',
               'amadeu',
               'amarildo',
               'amaro',
               'amauri',
               'americo',
               'amilton',
               'ananias',
               'ancelmo',
               'anderson',
               'andre',
               'andrei',
               'andrew',
               'andrey',
               'angelo',
               'anisio',
               'anselmo',
               'antenor',
               'anthony',
               'antonio',
               'antony',
               'aparecido',
               'apolo',
               'aquiles',
               'ari',
               'ariel',
               'ariovaldo',
               'aristides',
               'arlindo',
               'armando',
               'arnaldo',
               'aroldo',
               'arthur',
               'artur',
               'ary',
               'assis',
               'ataide',
               'atila',
               'augusto',
               'aurelio',
               'avelino',
               'bartolomeu',
               'beijamin',
               'benedito',
               'benicio',
               'benjamim',
               'benjamin',
               'bento',
               'bernado',
               'bernardo',
               'braz',
               'brendo',
               'brenno',
               'breno',
               'brian',
               'bruno',
               'caetano',
               'caio',
               'caique',
               'calebe',
               'camilo',
               'candido',
               'carlito',
               'carlos',
               'cassiano',
               'cassio',
               'caua',
               'cauan',
               'caue',
               'celio',
               'celso',
               'cesar',
               'cezar',
               'charles',
               'christian',
               'cicero',
               'ciro',
               'claudemir',
               'claudinei',
               'claudio',
               'claudionor',
               'clayton',
               'cleber',
               'cleiton',
               'clemente',
               'cleyton',
               'clodoaldo',
               'clovis',
               'conrado',
               'cosme',
               'cosmo',
               'cristian',
               'cristiano',
               'cristovao',
               'damiao',
               'daniel',
               'danilo',
               'dante',
               'darci',
               'dario',
               'davi',
               'david',
               'decio',
               'deivid',
               'dejair',
               'dener',
               'denilson',
               'denis',
               'diego',
               'dilson',
               'dimas',
               'diogo',
               'dionisio',
               'dirceu',
               'divino',
               'djalma',
               'domingo',
               'domingos',
               'donizete',
               'dorival',
               'douglas',
               'durval',
               'eder',
               'ederson',
               'edgar',
               'edilson',
               'edimilson',
               'edivan',
               'edmar',
               'edmilson',
               'edmundo',
               'edson',
               'eduardo',
               'edvaldo',
               'elcio',
               'eli',
               'elias',
               'eliezer',
               'elio',
               'eliseu',
               'elizeu',
               'eloi',
               'elton',
               'elvis',
               'emanoel',
               'emanuel',
               'emerson',
               'emilio',
               'enio',
               'enoque',
               'enrique',
               'enzo',
               'eraldo',
               'erasmo',
               'eric',
               'erick',
               'erico',
               'erik',
               'erike',
               'erivan',
               'ernani',
               'ernesto',
               'esdras',
               'esmael',
               'estevao',
               'euclides',
               'eudes',
               'eugenio',
               'eurico',
               'evaldo',
               'evandro',
               'evaristo',
               'everaldo',
               'everton',
               'ewerton',
               'expedito',
               'ezequias',
               'ezequiel',
               'fabiano',
               'fabio',
               'fabricio',
               'fagner',
               'fausto',
               'felipe',
               'felix',
               'fellipe',
               'fernado',
               'fernando',
               'filipe',
               'flavio',
               'floriano',
               'fracisco',
               'francimar',
               'francis',
               'francisco',
               'frank',
               'franklin',
               'franscisco',
               'fred',
               'frederico',
               'gabriel',
               'gaspar',
               'genesio',
               'genival',
               'genivaldo',
               'gentil',
               'george',
               'geovane',
               'geovani',
               'geraldo',
               'germano',
               'geronimo',
               'gerson',
               'getulio',
               'gian',
               'gil',
               'gilberto',
               'gildasio',
               'gildo',
               'gilmar',
               'gilson',
               'gilvan',
               'giovane',
               'giovani',
               'giovanni',
               'glauber',
               'glaucio',
               'glauco',
               'gleidson',
               'gleison',
               'goncalo',
               'gregorio',
               'guilherme',
               'gustavo',
               'gutemberg',
               'hamilton',
               'haroldo',
               'hebert',
               'hector',
               'heitor',
               'helder',
               'heleno',
               'helio',
               'helton',
               'henri',
               'henrique',
               'henry',
               'herbert',
               'hercules',
               'hermes',
               'hiago',
               'higor',
               'hilario',
               'hilton',
               'hudson',
               'hugo',
               'humberto',
               'iago',
               'ian',
               'icaro',
               'igo',
               'igor',
               'ildo',
               'inacio',
               'iran',
               'irineu',
               'isaac',
               'isaias',
               'isaque',
               'ismael',
               'israel',
               'italo',
               'itamar',
               'iuri',
               'ivaldo',
               'ivan',
               'ivanildo',
               'ivo',
               'izael',
               'izaias',
               'izaque',
               'jacinto',
               'jackson',
               'jaco',
               'jader',
               'jadson',
               'jailson',
               'jailton',
               'jaime',
               'jair',
               'jairo',
               'jaison',
               'jakson',
               'james',
               'jamil',
               'janderson',
               'janio',
               'jardel',
               'jean',
               'jeferson',
               'jefferson',
               'jeova',
               'jeremias',
               'jeronimo',
               'jesse',
               'jesus',
               'jhon',
               'jhonata',
               'jhonatas',
               'jhonny',
               'jhony',
               'joao',
               'joaquim',
               'jobson',
               'joel',
               'joelson',
               'john',
               'johnny',
               'jonas',
               'jonata',
               'jonatan',
               'jonatas',
               'jonatha',
               'jonathan',
               'jones',
               'jordan',
               'jorge',
               'josafa',
               'jose',
               'josias',
               'josue',
               'juan',
               'juarez',
               'jucelino',
               'julho',
               'julian',
               'juliano',
               'julio',
               'junio',
               'junior',
               'jurandir',
               'juscelino',
               'justino',
               'juvenal',
               'kaio',
               'kaique',
               'kaleb',
               'kaua',
               'kauan',
               'kaue',
               'kayo',
               'kayque',
               'kelvin',
               'kenedy',
               'kennedy',
               'kevin',
               'kleber',
               'laercio',
               'laerte',
               'laurindo',
               'lauro',
               'lazaro',
               'leandro',
               'lenilson',
               'leo',
               'leomar',
               'leonan',
               'leonardo',
               'leonel',
               'leonidas',
               'levi',
               'levy',
               'lincoln',
               'lincon',
               'lindomar',
               'lino',
               'lorenzo',
               'lorran',
               'lourenco',
               'lourival',
               'luan',
               'luca',
               'lucas',
               'lucca',
               'luciano',
               'lucio',
               'luigi',
               'luis',
               'luiz',
               'maciel',
               'madson',
               'magno',
               'maicon',
               'maike',
               'manoel',
               'manuel',
               'marcel',
               'marcelino',
               'marcello',
               'marcelo',
               'marciano',
               'marcilio',
               'marcio',
               'marco',
               'marcondes',
               'marcone',
               'marconi',
               'marcos',
               'marcus',
               'mariano',
               'marino',
               'mario',
               'marivaldo',
               'marlon',
               'martin',
               'martinho',
               'mateus',
               'matheus',
               'mathias',
               'matias',
               'mauricio',
               'maurilio',
               'mauro',
               'max',
               'maxsuel',
               'maxwell',
               'maycon',
               'messias',
               'micael',
               'michael',
               'michel',
               'miguel',
               'milton',
               'miqueias',
               'misael',
               'moacir',
               'moises',
               'murillo',
               'murilo',
               'narciso',
               'natal',
               'natalicio',
               'natalino',
               'natan',
               'natanael',
               'nathan',
               'nazareno',
               'nei',
               'nelio',
               'nelson',
               'neri',
               'nestor',
               'newton',
               'ney',
               'nicolas',
               'nildo',
               'nilo',
               'nilson',
               'nilton',
               'nivaldo',
               'noa',
               'noah',
               'noe',
               'noel',
               'odair',
               'odilon',
               'olavo',
               'olimpio',
               'oliver',
               'olivio',
               'omar',
               'onofre',
               'orlando',
               'oscar',
               'oseias',
               'osmar',
               'osni',
               'osvaldo',
               'oswaldo',
               'otacilio',
               'otavio',
               'otto',
               'ozeias',
               'pablo',
               'patricio',
               'patrick',
               'paulino',
               'paulo',
               'pedro',
               'peterson',
               'pierre',
               'plinio',
               'rael',
               'rafael',
               'rai',
               'raimundo',
               'ramiro',
               'ramom',
               'ramon',
               'rangel',
               'raniel',
               'raphael',
               'raul',
               'ravi',
               'ray',
               'reginaldo',
               'regis',
               'reinaldo',
               'renan',
               'renato',
               'rene',
               'rian',
               'ricardo',
               'richard',
               'rildo',
               'rinaldo',
               'riquelme',
               'rivaldo',
               'robert',
               'roberto',
               'robson',
               'rodolfo',
               'rodrigo',
               'roger',
               'rogerio',
               'romario',
               'romero',
               'romeu',
               'romildo',
               'romulo',
               'ronald',
               'ronaldo',
               'ronan',
               'rone',
               'ronei',
               'roney',
               'roni',
               'rony',
               'roque',
               'ruan',
               'rubem',
               'rubens',
               'rui',
               'ruy',
               'ryan',
               'saimon',
               'salatiel',
               'salomao',
               'salvador',
               'samir',
               'samuel',
               'sandoval',
               'sandro',
               'santiago',
               'saulo',
               'savio',
               'sebastiao',
               'sebatiao',
               'sergio',
               'severino',
               'sidnei',
               'sidney',
               'silas',
               'silvano',
               'silvestre',
               'silvino',
               'silvio',
               'simao',
               'sinval',
               'tadeu',
               'tales',
               'tarcisio',
               'tauan',
               'taylor',
               'teo',
               'teodoro',
               'thales',
               'thalles',
               'theo',
               'theodoro',
               'thiago',
               'thomas',
               'thomaz',
               'tiago',
               'tomas',
               'tomaz',
               'tony',
               'tulio',
               'uanderson',
               'ubirajara',
               'ubiratan',
               'ulisses',
               'vagner',
               'valcir',
               'valdeci',
               'valdemar',
               'valdemir',
               'valdir',
               'valdo',
               'valdomiro',
               'valentim',
               'valerio',
               'valmir',
               'valter',
               'vander',
               'vanderlei',
               'vanderley',
               'vando',
               'vicente',
               'victor',
               'vilmar',
               'vilson',
               'vinicios',
               'vinicius',
               'virgilio',
               'vitor',
               'vitorio',
               'vladimir',
               'wagner',
               'waldemar',
               'waldir',
               'wallace',
               'walmir',
               'walter',
               'wander',
               'wanderlei',
               'wanderley',
               'wanderson',
               'washington',
               'welinton',
               'wellington',
               'welton',
               'wendel',
               'wendell',
               'wesley',
               'weslley',
               'wiliam',
               'wilian',
               'william',
               'willian',
               'willians',
               'wilson',
               'wilton',
               'yago',
               'yan',
               'ygor',
               'yure',
               'yuri',
               'zacarias',
               'zaqueu',
               'ze'],
 'outros_fem': ['americana',
                'bahiana',
                'baiana',
                'brasileira',
                'estrangeira',
                'gaúcha',
                'goiana',
                'jamaicana',
                'japonesa',
                'pagodeira',
                'paraguaia',
                'sapatão',
                'solteira',
                'solteiras',
                'solteirinha',
                'solteirona'],
 'outros_masc': ['baiano',
                 'gaiteiro',
                 'gauchinho',
                 'gay',
                 'gaúcho',
                 'goiano',
                 'japonês',
                 'mineiro',
                 'padre',
                 'pagodeiro',
                 'pernambucano',
                 'solteirinho',
                 'solteiro',
                 'solteirão']}



def normalizar_nome_coluna(valor):
    texto = str(valor).strip().lower()
    texto = "".join(
        caractere
        for caractere in texto
        if caractere.isalnum()
    )
    return texto


def achar_coluna(colunas, nome_desejado):
    alvo = normalizar_nome_coluna(nome_desejado)

    for coluna in colunas:
        if normalizar_nome_coluna(coluna) == alvo:
            return coluna

    raise ValueError(
        f"Não encontrei a coluna '{nome_desejado}'. "
        f"Colunas encontradas: {list(colunas)}"
    )


def normalizar_palavra_alvo_para_busca(valor):
    if pd.isna(valor):
        return ""

    texto = str(valor).lower().strip()

    texto = "".join(
        caractere
        if caractere.isalpha() or caractere.isspace()
        else " "
        for caractere in texto
    )

    texto = re.sub(r"\s+", " ", texto).strip()

    return texto


def carregar_mapa_alvos_codificado():
    mapa = {}

    for classificacao, palavras in ALVOS_POR_CLASSIFICACAO.items():
        for valor in palavras:
            palavra = normalizar_palavra_alvo_para_busca(valor)

            if not palavra:
                continue

            if palavra in mapa:
                if mapa[palavra] != classificacao:
                    raise ValueError(
                        f"Classificação conflitante para '{palavra}': "
                        f"{mapa[palavra]} x {classificacao}"
                    )

                raise ValueError(
                    f"Alvo duplicado na lista codificada: '{palavra}'"
                )

            mapa[palavra] = classificacao

    if len(mapa) != 1569:
        raise ValueError(
            f"Quantidade inesperada de alvos codificados: {len(mapa)}. "
            "Esperado: 1569."
        )

    return mapa


def criar_padrao_substituicao(mapa):
    termos = sorted(
        mapa.keys(),
        key=lambda termo: (-len(termo), termo),
    )

    alternativas = []

    for termo in termos:
        parte = re.escape(termo)
        parte = parte.replace(r"\ ", r"\s+")
        alternativas.append(parte)

    return re.compile(
        rf"(?<![a-zà-öø-ÿ0-9_])(?:{'|'.join(alternativas)})(?![a-zà-öø-ÿ0-9_])",
        flags=re.IGNORECASE | re.UNICODE,
    )


MAPA_ALVOS = carregar_mapa_alvos_codificado()
PADRAO_ALVOS = criar_padrao_substituicao(
    MAPA_ALVOS
)


def substituir_alvos(texto):
    if pd.isna(texto):
        return ""

    texto = str(texto)

    def trocar(match):
        palavra = normalizar_palavra_alvo_para_busca(
            match.group(0)
        )

        classificacao = MAPA_ALVOS.get(
            palavra
        )

        if not classificacao:
            return match.group(0)

        CONTAGEM_SUBSTITUICOES[
            classificacao
        ] += 1

        return classificacao

    return PADRAO_ALVOS.sub(
        trocar,
        texto
    )


def detectar_encoding(caminho):
    for encoding in [
        "utf-8-sig",
        "utf-8",
        "cp1252",
        "latin1",
    ]:
        try:
            pd.read_csv(
                caminho,
                encoding=encoding,
                nrows=5,
                dtype=str,
            )
            return encoding

        except UnicodeDecodeError:
            continue

    return "latin1"


def processar_arquivo(nome, caminho_entrada, caminho_saida):
    if caminho_saida.exists():
        caminho_saida.unlink()

    encoding = detectar_encoding(
        caminho_entrada
    )

    reader = pd.read_csv(
        caminho_entrada,
        encoding=encoding,
        chunksize=CHUNKSIZE,
        dtype=str,
        low_memory=False,
    )

    primeira_escrita = True
    total_linhas = 0

    for numero_chunk, chunk in enumerate(
        reader,
        start=1,
    ):
        chunk = chunk.copy()

        coluna_letra = achar_coluna(
            chunk.columns,
            "Letra da Música",
        )

        chunk[coluna_letra] = (
            chunk[coluna_letra]
            .apply(substituir_alvos)
        )

        chunk.to_csv(
            caminho_saida,
            mode="w" if primeira_escrita else "a",
            header=primeira_escrita,
            index=False,
            encoding="utf-8-sig",
            quoting=csv.QUOTE_ALL,
        )

        primeira_escrita = False
        total_linhas += len(chunk)

        print(
            f"{nome} | chunk {numero_chunk} | "
            f"linhas processadas: {total_linhas}"
        )

    print(
        f"{nome} finalizado: {caminho_saida}"
    )


def main():
    print(
        f"Alvos carregados: {len(MAPA_ALVOS)}"
    )

    for nome, caminho_entrada in (
        ARQUIVOS_ENTRADA.items()
    ):
        processar_arquivo(
            nome,
            caminho_entrada,
            ARQUIVOS_SAIDA[nome],
        )

    print(
        "\nSubstituições por pmi_classificacao:"
    )

    for classificacao, quantidade in sorted(
        CONTAGEM_SUBSTITUICOES.items()
    ):
        print(
            f"{classificacao}: {quantidade}"
        )


if __name__ == "__main__":
    main()
